### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by mozgbrasil** [Fleshgrinder/php-url-validator#5]
Good morning my friends

How should this extension be used?

Tried as follows but error returned

$isValid = new \Fleshgrinder\Validator\URL\validate($url);

**Comment by Fleshgrinder** [comment]
Hey @mozgbrasil, did you already have a look at [`thephpleague/uri`](https://github.com/thephpleague/uri)? It’s much better maintained than this package.

**Comment by mozgbrasil** [comment]
Good Morning

Thanks for the tip
